variables:
  #RETROSPEC_TEMPLATES_DIR: /root/.retrospec/repos/retrospec-puppet-templates
before_script:
  - gem install bundler
  - bundle install --without development build
  - bundle exec ruby lib/retrospec/plugins/v1/plugin/templates/clone-hook

image: ruby:2.1

ruby193:
  stage: test
  script:
    - "bundle exec rake spec"
  image: ruby:1.9.3
  allow_failure: true

ruby2.0:
  stage: test
  script:
    - "bundle exec rake spec"
  image: ruby:2.0

ruby2.1:
  stage: test
  script:
    - "bundle exec rake spec"
  image: ruby:2.1

ruby2.2:
  stage: test
  script:
    - "bundle exec rake spec"
  image: ruby:2.2

ruby2.3:
  stage: test
  script:
    - "bundle exec rake spec"
  image: ruby:2.3

stages:
  - validate
  - test
  - release
  - deploy

rubocop_ruby:
  stage: validate
  allow_failure: true
  only:
    - branches
  tags:
    - ruby2.2
  script:
    - bundle install
    - bundle exec rubocop -D

bump_and_tag:
  type: release
  when: manual
  tags:
    - ruby2.2
  only:
    - master@nwops/puppet-retrospec
  script:
    - gem install release_me
    - bump_and_tag

production:
  tags:
    - ruby2.2
  before_script:
    - gem install dpl
  type: deploy
  script:
    - dpl --provider=rubygems --api-key=$RUBYGEMS_API_KEY
  only:
    - tags
